### ISSUE TITLE
[Feature Request] WiFi Off to survive after wake from sleep

### ISSUE THREAD

**Issue by racka98** [OpenIntelWireless/HeliPort#205] opened 2020-10-15 19:26 UTC
**Is your feature request related to a problem? Please describe.**
Whenever i turn off wifi and put the computer to sleep, it would turn back on when i wake from sleep and auto connect to a wifi if present or the icon will be flashing continuously when no network is available 

**Describe the solution you'd like**
Make the off state survive after wake from sleep

**Describe alternatives you've considered**
I've always had to turn it back off manually or quit the app

Opencore 0.6.2
macOS 10.15.7 Catalina

**Comment by williambj1** [comment] 2020-10-16 01:03
Duplicate of #184

**Closed by williambj1** 2020-10-16 01:03 UTC
