### ISSUE TITLE
launch heliport upon login

### ISSUE THREAD

**Issue by desmondyipyc** [OpenIntelWireless/HeliPort#190] opened 2020-09-05 23:40 UTC
is it possible to have an option to launch heliport upon launching?

always have to manually open up heliport to have wifi

**Comment by williambj1** [comment] 2020-09-06 04:20
Duplicate of #42

**Comment by williambj1** [comment] 2020-09-06 04:20
Instructions are available in our docs page

**Closed by williambj1** 2020-09-06 04:20 UTC
