### ISSUE TITLE
[Bug] More StatusMenu glitches

### ISSUE THREAD

**Issue by williambj1** [OpenIntelWireless/HeliPort#29] opened 2020-06-22 04:07 UTC
**Describe the bug**
1. WiFiMenuItemView shows duplicated items with different fonts
2. Long SSIDs (e.g. From wireless projectors/printers) will be wrapped

**To Reproduce**
1. Scan SSIDs for a while
2. Connect to your Wi-Fi
3. Open the menu again
4. Wait for a while

**Expected behavior**
No duplications, no line wraps

**Screenshots**

![image](https://user-images.githubusercontent.com/45396585/85247780-754d4300-b481-11ea-8ed4-9b7207e4a703.png)

- Duplication: `ssdt`
- Line wrap: `DIRECT-`

**Environment (please complete the following information):**
 - OS Version: 10.15.4 (19E287)
 - Software Version: 562089e6d5aba95ad0b0854f18132292d7a59f1a

**Additional context**
This issue existed for quite a long time.

**Comment by ErrorErrorError** [comment] 2020-06-22 04:12
> no line wraps

So the expected behavior of StatusMenu is to expand the width of the whole view correct? I actually had mine working like that but I might of deleted that code trying to figure out the issue with the  different widths of WiFiMenuItemView.

**Comment by williambj1** [comment] 2020-06-22 04:51
> So the expected behavior of StatusMenu is to expand the width of the whole view correct?

Yes, that's how Apple's app behaves, I've verified this on a MacBook Pro.

**Comment by ErrorErrorError** [comment] 2020-06-23 06:47
> 2\. Long SSIDs (e.g. From wireless projectors/printers) will be wrapped

Now, I am almost done finishing implementing however I currently am not able to access my mac due to someone else borrowing it. There is just one small thing that I am not sure if it happens on a real mac but whenever texts are below minimum, and then the next search happens and turns out it's a long ssid, does the whole NSMenu expand or does it get truncated and then in the next time you close and open the menu is it supposed to look fine?  I will upload a video in just a moment on what I mean.

**Comment by ErrorErrorError** [comment] 2020-07-09 03:10
Sorry for the multiple references, I thought I already removed the reference.

**Comment by Goshin** [comment] 2020-07-10 11:06
Fixed in https://github.com/OpenIntelWireless/HeliPort/commit/1cf4020f946372e574a3782f3eac76b47a9c1cdd and https://github.com/OpenIntelWireless/HeliPort/commit/bcfccca7c9793be6887725fca3e340f880cc124c

**Closed by Goshin** 2020-07-10 11:06 UTC
Labels: bug
