### ISSUE TITLE
[Feature Request] New Icon for Menubar

### ISSUE THREAD

**Issue by R-Teer** [OpenIntelWireless/HeliPort#206] opened 2020-10-21 18:08 UTC
Is there a possibility to update the menubar icon to be more in line with the newest Mac OS version?

As we are upon release of Big Sur, it would be great to see an implementation that better suits the new UI such as:

[See Here](https://icons8.com/icon/85509/wi-fi)

**Comment by williambj1** [comment] 2020-10-21 23:42
Duplicate of #174

**Comment by williambj1** [comment] 2020-10-21 23:42
Duplicate of #182

**Closed by williambj1** 2020-10-21 23:42 UTC
