### ISSUE TITLE
Prioritize/Forget WiFi Networks

### ISSUE THREAD

**Issue by francisceril** [OpenIntelWireless/HeliPort#137] opened 2020-07-29 09:20 UTC
Since the WiFi is currently running as Ethernet, there's no native way to Prioritize or Forget networks. It would be helpful to have a workaround option for this on the app.

Or if someone knows how to completely prioritize or remove older WiFi networks, please do comment. My hack always connects to an old WiFi network every cold start.

**Comment by francisceril** [comment] 2020-07-29 09:21
Duplicate and already solved. Sorry!

**Comment by Goshin** [comment] 2020-07-29 09:42
https://github.com/OpenIntelWireless/HeliPort/issues/81

**Comment by williambj1** [comment] 2020-07-29 10:23
Duplicate of #81

**Closed by williambj1** 2020-07-29 10:23 UTC
