### ISSUE TITLE
[Feature Request]3 suggestions: Forget Network...

### ISSUE THREAD

**Issue by XHL669** [OpenIntelWireless/HeliPort#109] opened 2020-07-19 06:15 UTC
**Is your feature request related to a problem? Please describe.**
1.Forget Netwok: When the user check `remember network` but input the wrong password unexpectedly, the function `forget network` will be used. Otherwise, the user can only to delete it in the `keychain access`.
2.Menu: I think you could add a menu. When the pointer is on the WLAN’s name, the menu list some commonly used functions such as `disconnect`, `forget network` and other possible choices.
3.Disconnect automatically: Errr, when HeliPort quit, the network is disconnected automatically, although I know HeliPort is just a GUI for itlwm. 

**Additional context**
I photoshop some images that meet my requirement.
`Forget network` could be like this:
![1](https://user-images.githubusercontent.com/63577165/87868389-af016300-c9c7-11ea-8091-7d89308ccc7d.png)
menu is like this:
![2](https://user-images.githubusercontent.com/63577165/87868589-16201700-c9ca-11ea-83a4-eb13f9cc72cc.png)

**Comment by williambj1** [comment] 2020-07-19 06:29
Duplicate of #81

**Closed by williambj1** 2020-07-19 06:29 UTC

**Comment by williambj1** [comment] 2020-07-19 06:52
We already had a disconnect menu, you could let it appear by holding option while opening HeliPort.

Other functions will be added in a separate window

Thanks for your suggestion.
